### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2714' 

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tmn#36]
Logs:
```
Updating masternode Tomo_H:

Containers

Stopping Tomo_H_metrics... Traceback (most recent call last):
File "/home/opsz/.local/bin/tmn", line 11, in <module>
sys.exit(main())
File "/home/opsz/.local/lib/python3.5/site-packages/click/core.py", line 764, in call
return self.main(args, kwargs)
File "/home/opsz/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/home/opsz/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/opsz/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, ctx.params)
File "/home/opsz/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
return callback(args, kwargs)
File "/home/opsz/.local/lib/python3.5/site-packages/tmn/tmn.py", line 163, in update
display.step_close('\u2714')
File "/home/opsz/.local/lib/python3.5/site-packages/tmn/display.py", line 23, in wrapper
print(pastel.colorize(function(*args, kwargs)))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2714' in position 5: ordinal not in range(256)
```
I will be fix if change PYTHONIOENCODING env:
```
export PYTHONIOENCODING=utf-8
```

If can easily fix in `tmn`, let fix it.
In another way, just update the docs in `troubleshooting` section

**Comment by etienne-napoleone** [comment]
Might be fixable with something like:
`u'\u27143'.encode('utf-8')`
instead of:
`' ✓'`
